
version: "3.7"

services:

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
       - ./src/:/Project_TypeScript
  
  ts-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/Project_TypeScript/src
      - ./nodemon.json:/Project_TypeScript/nodemon.json
    container_name: ts-node-docker
    expose:
      - '3333'
    ports:
      - '3333:3333'
    env_file:
      - .env
    command: npm run dev